package com.google.android.gms.measurement.internal;

import android.content.Context;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

/* loaded from: classes.dex */
public final class o {
    public static x3<Long> A;
    public static x3<Boolean> A0;
    public static x3<Long> B;
    public static x3<Boolean> B0;
    public static x3<Integer> C;
    public static x3<Boolean> C0;
    public static x3<Long> D;
    public static x3<Boolean> D0;
    public static x3<Integer> E;
    public static x3<Boolean> E0;
    public static x3<Integer> F;
    public static x3<Boolean> F0;
    public static x3<Long> G;
    public static x3<Boolean> G0;
    public static x3<Boolean> H;
    public static x3<Boolean> H0;
    public static x3<String> I;
    public static x3<Boolean> I0;
    public static x3<Long> J;
    public static x3<Boolean> J0;
    public static x3<Integer> K;
    public static x3<Boolean> K0;
    public static x3<Double> L;
    public static x3<Boolean> L0;
    public static x3<Integer> M;
    public static x3<Boolean> M0;
    public static x3<Boolean> N;
    public static x3<Boolean> N0;
    public static x3<Boolean> O;
    public static x3<Boolean> O0;
    public static x3<Boolean> P;
    public static x3<Boolean> P0;
    public static x3<Boolean> Q;
    public static x3<Boolean> Q0;
    public static x3<Boolean> R;
    public static x3<Boolean> R0;
    public static x3<Boolean> S;
    public static x3<Boolean> S0;
    public static x3<Boolean> T;
    public static x3<Boolean> T0;
    public static x3<Boolean> U;
    public static x3<Boolean> U0;
    public static x3<Boolean> V;
    public static x3<Boolean> V0;
    public static x3<Boolean> W;
    public static x3<Boolean> W0;
    public static x3<Boolean> X;
    public static x3<Boolean> X0;
    public static x3<Boolean> Y;
    public static x3<Boolean> Y0;
    public static x3<Boolean> Z;
    public static x3<Boolean> Z0;
    private static List<x3<?>> a = Collections.synchronizedList(new ArrayList());
    public static x3<Boolean> a0;
    public static x3<Long> b;
    public static x3<Boolean> b0;
    public static x3<Long> c;
    public static x3<Boolean> c0;
    public static x3<Long> d;
    public static x3<Boolean> d0;
    public static x3<String> e;
    public static x3<Boolean> e0;
    public static x3<String> f;
    public static x3<Boolean> f0;
    public static x3<Integer> g;
    public static x3<Boolean> g0;
    public static x3<Integer> h;
    public static x3<Boolean> h0;
    public static x3<Integer> i;
    public static x3<Boolean> i0;
    public static x3<Integer> j;
    public static x3<Boolean> j0;
    public static x3<Integer> k;
    public static x3<Boolean> k0;
    public static x3<Integer> l;
    public static x3<Boolean> l0;
    public static x3<Integer> m;
    public static x3<Boolean> m0;
    public static x3<Integer> n;
    public static x3<Boolean> n0;
    public static x3<Integer> o;
    public static x3<Boolean> o0;
    public static x3<Integer> p;
    public static x3<Boolean> p0;
    public static x3<String> q;
    public static x3<Boolean> q0;
    public static x3<Long> r;
    public static x3<Boolean> r0;
    public static x3<Long> s;
    public static x3<Boolean> s0;
    public static x3<Long> t;
    public static x3<Boolean> t0;
    public static x3<Long> u;
    public static x3<Boolean> u0;
    public static x3<Long> v;
    public static x3<Boolean> v0;
    public static x3<Long> w;
    public static x3<Boolean> w0;
    public static x3<Long> x;
    public static x3<Boolean> x0;
    public static x3<Long> y;
    public static x3<Boolean> y0;
    public static x3<Long> z;
    public static x3<Boolean> z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, 10000L, r.a);
        c = a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, q.a);
        d = a("measurement.config.cache_time", 86400000L, 3600000L, f0.a);
        e = a("measurement.config.url_scheme", "https", "https", s0.a);
        f = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", c1.a);
        g = a("measurement.upload.max_bundles", 100, 100, p1.a);
        h = a("measurement.upload.max_batch_size", 65536, 65536, y1.a);
        i = a("measurement.upload.max_bundle_size", 65536, 65536, m2.a);
        j = a("measurement.upload.max_events_per_bundle", 1000, 1000, v2.a);
        k = a("measurement.upload.max_events_per_day", 100000, 100000, j3.a);
        l = a("measurement.upload.max_error_events_per_day", 1000, 1000, t.a);
        m = a("measurement.upload.max_public_events_per_day", 50000, 50000, x.a);
        n = a("measurement.upload.max_conversions_per_day", 500, 500, w.a);
        o = a("measurement.upload.max_realtime_events_per_day", 10, 10, a0.a);
        p = a("measurement.store.max_stored_events_per_app", 100000, 100000, y.a);
        q = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", c0.a);
        r = a("measurement.upload.backoff_period", 43200000L, 43200000L, b0.a);
        s = a("measurement.upload.window_interval", 3600000L, 3600000L, e0.a);
        t = a("measurement.upload.interval", 3600000L, 3600000L, d0.a);
        u = a("measurement.upload.realtime_upload_interval", 10000L, 10000L, g0.a);
        v = a("measurement.upload.debug_upload_interval", 1000L, 1000L, i0.a);
        w = a("measurement.upload.minimum_delay", 500L, 500L, h0.a);
        x = a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, k0.a);
        y = a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, j0.a);
        z = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, m0.a);
        A = a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, l0.a);
        B = a("measurement.upload.retry_time", 1800000L, 1800000L, o0.a);
        C = a("measurement.upload.retry_count", 6, 6, n0.a);
        D = a("measurement.upload.max_queue_time", 2419200000L, 2419200000L, q0.a);
        E = a("measurement.lifetimevalue.max_currency_tracked", 4, 4, p0.a);
        F = a("measurement.audience.filter_result_max_count", 200, 200, r0.a);
        G = a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, u0.a);
        H = a("measurement.test.boolean_flag", false, false, t0.a);
        I = a("measurement.test.string_flag", "---", "---", w0.a);
        J = a("measurement.test.long_flag", -1L, -1L, v0.a);
        K = a("measurement.test.int_flag", -2, -2, y0.a);
        Double valueOf = Double.valueOf(-3.0d);
        L = a("measurement.test.double_flag", valueOf, valueOf, x0.a);
        M = a("measurement.experiment.max_ids", 50, 50, b1.a);
        N = a("measurement.validation.internal_limits_internal_event_params", false, false, z0.a);
        O = a("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", false, false, d1.a);
        P = a("measurement.client.sessions.session_id_enabled", true, true, f1.a);
        Q = a("measurement.service.sessions.session_number_enabled", true, true, e1.a);
        R = a("measurement.client.sessions.background_sessions_enabled", true, true, h1.a);
        S = a("measurement.client.sessions.remove_expired_session_properties_enabled", true, true, g1.a);
        T = a("measurement.service.sessions.session_number_backfill_enabled", true, true, j1.a);
        U = a("measurement.service.sessions.remove_disabled_session_number", true, true, i1.a);
        V = a("measurement.client.sessions.start_session_before_view_screen", true, true, l1.a);
        W = a("measurement.client.sessions.check_on_startup", true, true, k1.a);
        X = a("measurement.collection.firebase_global_collection_flag_enabled", true, true, n1.a);
        Y = a("measurement.collection.efficient_engagement_reporting_enabled", false, false, m1.a);
        Z = a("measurement.collection.redundant_engagement_removal_enabled", false, false, o1.a);
        a0 = a("measurement.personalized_ads_signals_collection_enabled", true, true, r1.a);
        b0 = a("measurement.personalized_ads_property_translation_enabled", true, true, q1.a);
        c0 = a("measurement.upload.disable_is_uploader", true, true, t1.a);
        d0 = a("measurement.experiment.enable_experiment_reporting", true, true, s1.a);
        e0 = a("measurement.collection.log_event_and_bundle_v2", true, true, v1.a);
        f0 = a("measurement.quality.checksum", false, false, null);
        g0 = a("measurement.module.collection.conditionally_omit_admob_app_id", true, true, u1.a);
        h0 = a("measurement.sdk.dynamite.use_dynamite2", false, false, x1.a);
        i0 = a("measurement.sdk.dynamite.allow_remote_dynamite", false, false, w1.a);
        j0 = a("measurement.sdk.collection.validate_param_names_alphabetical", false, false, z1.a);
        k0 = a("measurement.collection.event_safelist", true, true, c2.a);
        l0 = a("measurement.service.audience.scoped_filters_v27", true, true, a2.a);
        m0 = a("measurement.service.audience.session_scoped_event_aggregates", true, true, e2.a);
        n0 = a("measurement.service.audience.session_scoped_user_engagement", true, true, d2.a);
        o0 = a("measurement.service.audience.scoped_engagement_removal_when_session_expired", true, true, g2.a);
        p0 = a("measurement.client.audience.scoped_engagement_removal_when_session_expired", true, true, f2.a);
        q0 = a("measurement.service.audience.remove_disabled_session_scoped_user_engagement", false, false, i2.a);
        r0 = a("measurement.service.audience.use_bundle_timestamp_for_property_filters", true, true, h2.a);
        s0 = a("measurement.service.audience.fix_prepending_previous_sequence_timestamp", true, true, k2.a);
        a("measurement.service.audience.invalidate_config_cache_after_app_unisntall", true, true, j2.a);
        t0 = a("measurement.service.audience.fix_skip_audience_with_failed_filters", true, true, l2.a);
        u0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, o2.a);
        v0 = a("measurement.audience.refresh_event_count_filters_timestamp", false, false, n2.a);
        w0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, q2.a);
        x0 = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, p2.a);
        y0 = a("measurement.app_launch.event_ordering_fix", false, false, s2.a);
        z0 = a("measurement.sdk.collection.last_deep_link_referrer2", false, false, r2.a);
        A0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, u2.a);
        B0 = a("measurement.sdk.collection.last_gclid_from_referrer2", false, false, t2.a);
        C0 = a("measurement.sdk.collection.worker_thread_referrer", true, true, w2.a);
        D0 = a("measurement.sdk.collection.enable_extend_user_property_size", true, true, y2.a);
        E0 = a("measurement.upload.file_lock_state_check", false, false, x2.a);
        F0 = a("measurement.sampling.calculate_bundle_timestamp_before_sampling", true, true, a3.a);
        G0 = a("measurement.ga.ga_app_id", false, false, z2.a);
        H0 = a("measurement.lifecycle.app_backgrounded_tracking", true, true, d3.a);
        I0 = a("measurement.lifecycle.app_in_background_parameter", false, false, b3.a);
        J0 = a("measurement.integration.disable_firebase_instance_id", false, false, f3.a);
        K0 = a("measurement.lifecycle.app_backgrounded_engagement", false, false, e3.a);
        L0 = a("measurement.service.fix_gmp_version", false, false, h3.a);
        M0 = a("measurement.collection.service.update_with_analytics_fix", false, false, g3.a);
        N0 = a("measurement.service.disable_install_state_reporting", false, false, i3.a);
        O0 = a("measurement.service.use_appinfo_modified", false, false, l3.a);
        P0 = a("measurement.client.firebase_feature_rollout.v1.enable", true, true, k3.a);
        Q0 = a("measurement.client.sessions.check_on_reset_and_enable", false, false, n3.a);
        R0 = a("measurement.config.string.always_update_disk_on_set", false, false, m3.a);
        S0 = a("measurement.scheduler.task_thread.cleanup_on_exit", false, false, p3.a);
        T0 = a("measurement.upload.file_truncate_fix", false, false, o3.a);
        U0 = a("measurement.lifecycle.app_background_timestamp_when_backgrounded", true, true, r3.a);
        V0 = a("measurement.engagement_time_main_thread", false, false, q3.a);
        W0 = a("measurement.sdk.referrer.delayed_install_referrer_api", false, false, t3.a);
        X0 = a("measurement.logging.improved_messaging_q4_2019_client", true, true, s.a);
        Y0 = a("measurement.logging.improved_messaging_q4_2019_service", true, true, v.a);
        Z0 = a("measurement.gold.enhanced_ecommerce.format_logs", false, false, u.a);
    }

    private static <V> x3<V> a(String str, V v2, V v3, v3<V> v3Var) {
        x3<V> x3Var = new x3<>(str, v2, v3, v3Var);
        a.add(x3Var);
        return x3Var;
    }

    public static Map<String, String> a(Context context) {
        com.google.android.gms.internal.measurement.i1 a2 = com.google.android.gms.internal.measurement.i1.a(context.getContentResolver(), com.google.android.gms.internal.measurement.u1.a("com.google.android.gms.measurement"));
        return a2 == null ? Collections.emptyMap() : a2.a();
    }

    public static final /* synthetic */ Long z0() {
        ka kaVar = u3.a;
        return Long.valueOf(com.google.android.gms.internal.measurement.r8.j());
    }
}
