package com.viewpagerindicator;

import android.R;

/* loaded from: classes.dex */
public final class R$styleable {
    public static final int CirclePageIndicator_android_background = 1;
    public static final int CirclePageIndicator_android_orientation = 0;
    public static final int CirclePageIndicator_centered = 2;
    public static final int CirclePageIndicator_fillColor = 3;
    public static final int CirclePageIndicator_pageColor = 4;
    public static final int CirclePageIndicator_radius = 5;
    public static final int CirclePageIndicator_snap = 6;
    public static final int CirclePageIndicator_strokeColor = 7;
    public static final int CirclePageIndicator_strokeWidth = 8;
    public static final int ColorStateListItem_alpha = 2;
    public static final int ColorStateListItem_android_alpha = 1;
    public static final int ColorStateListItem_android_color = 0;
    public static final int CoordinatorLayout_Layout_android_layout_gravity = 0;
    public static final int CoordinatorLayout_Layout_layout_anchor = 1;
    public static final int CoordinatorLayout_Layout_layout_anchorGravity = 2;
    public static final int CoordinatorLayout_Layout_layout_behavior = 3;
    public static final int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
    public static final int CoordinatorLayout_Layout_layout_insetEdge = 5;
    public static final int CoordinatorLayout_Layout_layout_keyline = 6;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int FontFamilyFont_android_font = 0;
    public static final int FontFamilyFont_android_fontStyle = 2;
    public static final int FontFamilyFont_android_fontVariationSettings = 4;
    public static final int FontFamilyFont_android_fontWeight = 1;
    public static final int FontFamilyFont_android_ttcIndex = 3;
    public static final int FontFamilyFont_font = 5;
    public static final int FontFamilyFont_fontStyle = 6;
    public static final int FontFamilyFont_fontVariationSettings = 7;
    public static final int FontFamilyFont_fontWeight = 8;
    public static final int FontFamilyFont_ttcIndex = 9;
    public static final int FontFamily_fontProviderAuthority = 0;
    public static final int FontFamily_fontProviderCerts = 1;
    public static final int FontFamily_fontProviderFetchStrategy = 2;
    public static final int FontFamily_fontProviderFetchTimeout = 3;
    public static final int FontFamily_fontProviderPackage = 4;
    public static final int FontFamily_fontProviderQuery = 5;
    public static final int GradientColorItem_android_color = 0;
    public static final int GradientColorItem_android_offset = 1;
    public static final int GradientColor_android_centerColor = 7;
    public static final int GradientColor_android_centerX = 3;
    public static final int GradientColor_android_centerY = 4;
    public static final int GradientColor_android_endColor = 1;
    public static final int GradientColor_android_endX = 10;
    public static final int GradientColor_android_endY = 11;
    public static final int GradientColor_android_gradientRadius = 5;
    public static final int GradientColor_android_startColor = 0;
    public static final int GradientColor_android_startX = 8;
    public static final int GradientColor_android_startY = 9;
    public static final int GradientColor_android_tileMode = 6;
    public static final int GradientColor_android_type = 2;
    public static final int LinePageIndicator_android_background = 0;
    public static final int LinePageIndicator_centered = 1;
    public static final int LinePageIndicator_gapWidth = 2;
    public static final int LinePageIndicator_lineWidth = 3;
    public static final int LinePageIndicator_selectedColor = 4;
    public static final int LinePageIndicator_strokeWidth = 5;
    public static final int LinePageIndicator_unselectedColor = 6;
    public static final int TitlePageIndicator_android_background = 2;
    public static final int TitlePageIndicator_android_textColor = 1;
    public static final int TitlePageIndicator_android_textSize = 0;
    public static final int TitlePageIndicator_clipPadding = 3;
    public static final int TitlePageIndicator_footerColor = 4;
    public static final int TitlePageIndicator_footerIndicatorHeight = 5;
    public static final int TitlePageIndicator_footerIndicatorStyle = 6;
    public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 7;
    public static final int TitlePageIndicator_footerLineHeight = 8;
    public static final int TitlePageIndicator_footerPadding = 9;
    public static final int TitlePageIndicator_linePosition = 10;
    public static final int TitlePageIndicator_selectedBold = 11;
    public static final int TitlePageIndicator_selectedColor = 12;
    public static final int TitlePageIndicator_titlePadding = 13;
    public static final int TitlePageIndicator_topPadding = 14;
    public static final int UnderlinePageIndicator_android_background = 0;
    public static final int UnderlinePageIndicator_fadeDelay = 1;
    public static final int UnderlinePageIndicator_fadeLength = 2;
    public static final int UnderlinePageIndicator_fades = 3;
    public static final int UnderlinePageIndicator_selectedColor = 4;
    public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
    public static final int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
    public static final int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
    public static final int ViewPagerIndicator_vpiTabPageIndicatorStyle = 3;
    public static final int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 4;
    public static final int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
    public static final int[] CirclePageIndicator = {R.attr.orientation, R.attr.background, com.mtni.myirancell.R.attr.centered, com.mtni.myirancell.R.attr.fillColor, com.mtni.myirancell.R.attr.pageColor, com.mtni.myirancell.R.attr.radius, com.mtni.myirancell.R.attr.snap, com.mtni.myirancell.R.attr.strokeColor, com.mtni.myirancell.R.attr.strokeWidth};
    public static final int[] ColorStateListItem = {R.attr.color, R.attr.alpha, com.mtni.myirancell.R.attr.alpha};
    public static final int[] CoordinatorLayout = {com.mtni.myirancell.R.attr.keylines, com.mtni.myirancell.R.attr.statusBarBackground};
    public static final int[] CoordinatorLayout_Layout = {R.attr.layout_gravity, com.mtni.myirancell.R.attr.layout_anchor, com.mtni.myirancell.R.attr.layout_anchorGravity, com.mtni.myirancell.R.attr.layout_behavior, com.mtni.myirancell.R.attr.layout_dodgeInsetEdges, com.mtni.myirancell.R.attr.layout_insetEdge, com.mtni.myirancell.R.attr.layout_keyline};
    public static final int[] FontFamily = {com.mtni.myirancell.R.attr.fontProviderAuthority, com.mtni.myirancell.R.attr.fontProviderCerts, com.mtni.myirancell.R.attr.fontProviderFetchStrategy, com.mtni.myirancell.R.attr.fontProviderFetchTimeout, com.mtni.myirancell.R.attr.fontProviderPackage, com.mtni.myirancell.R.attr.fontProviderQuery};
    public static final int[] FontFamilyFont = {R.attr.font, R.attr.fontWeight, R.attr.fontStyle, R.attr.ttcIndex, R.attr.fontVariationSettings, com.mtni.myirancell.R.attr.font, com.mtni.myirancell.R.attr.fontStyle, com.mtni.myirancell.R.attr.fontVariationSettings, com.mtni.myirancell.R.attr.fontWeight, com.mtni.myirancell.R.attr.ttcIndex};
    public static final int[] GradientColor = {R.attr.startColor, R.attr.endColor, R.attr.type, R.attr.centerX, R.attr.centerY, R.attr.gradientRadius, R.attr.tileMode, R.attr.centerColor, R.attr.startX, R.attr.startY, R.attr.endX, R.attr.endY};
    public static final int[] GradientColorItem = {R.attr.color, R.attr.offset};
    public static final int[] LinePageIndicator = {R.attr.background, com.mtni.myirancell.R.attr.centered, com.mtni.myirancell.R.attr.gapWidth, com.mtni.myirancell.R.attr.lineWidth, com.mtni.myirancell.R.attr.selectedColor, com.mtni.myirancell.R.attr.strokeWidth, com.mtni.myirancell.R.attr.unselectedColor};
    public static final int[] TitlePageIndicator = {R.attr.textSize, R.attr.textColor, R.attr.background, com.mtni.myirancell.R.attr.clipPadding, com.mtni.myirancell.R.attr.footerColor, com.mtni.myirancell.R.attr.footerIndicatorHeight, com.mtni.myirancell.R.attr.footerIndicatorStyle, com.mtni.myirancell.R.attr.footerIndicatorUnderlinePadding, com.mtni.myirancell.R.attr.footerLineHeight, com.mtni.myirancell.R.attr.footerPadding, com.mtni.myirancell.R.attr.linePosition, com.mtni.myirancell.R.attr.selectedBold, com.mtni.myirancell.R.attr.selectedColor, com.mtni.myirancell.R.attr.titlePadding, com.mtni.myirancell.R.attr.topPadding};
    public static final int[] UnderlinePageIndicator = {R.attr.background, com.mtni.myirancell.R.attr.fadeDelay, com.mtni.myirancell.R.attr.fadeLength, com.mtni.myirancell.R.attr.fades, com.mtni.myirancell.R.attr.selectedColor};
    public static final int[] ViewPagerIndicator = {com.mtni.myirancell.R.attr.vpiCirclePageIndicatorStyle, com.mtni.myirancell.R.attr.vpiIconPageIndicatorStyle, com.mtni.myirancell.R.attr.vpiLinePageIndicatorStyle, com.mtni.myirancell.R.attr.vpiTabPageIndicatorStyle, com.mtni.myirancell.R.attr.vpiTitlePageIndicatorStyle, com.mtni.myirancell.R.attr.vpiUnderlinePageIndicatorStyle};

    private R$styleable() {
    }
}
